version: '3'

services:
  node:
    build:
      context: docker/node
    working_dir: /home/node/app
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    environment:
      HOST: 0.0.0.0
      PORT: 3005
    expose:
      - 3005
    volumes:
      - ./:/home/node/app
      - ./docker/node/bootstrap.sh:/usr/local/bin/bootstrap.sh
    command: sh -c 'yarn && yarn dev'
    restart: ${RESTART}
